version: '3'

services:
  # node-queue-mail-sender:
  #   build:
  #       context: ./
  #       dockerfile: Dockerfile
  #   container_name: node-queue-mail-sender
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "3003:3003"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local